/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.text.NumberFormat;

/**
 *
 * @author arauj
 */
public class CalculoImpostos extends javax.swing.JFrame {

    /**
     * Creates new form CalculoImpostos
     */
    public CalculoImpostos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelValorNotaFiscal = new javax.swing.JLabel();
        jTextFieldValorNotaFiscal = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();
        jLabelISS = new javax.swing.JLabel();
        jTextFieldISS = new javax.swing.JTextField();
        jLabelCONFINS = new javax.swing.JLabel();
        jTextFieldCONFINS = new javax.swing.JTextField();
        jLabelPIS = new javax.swing.JLabel();
        jTextFieldPIS = new javax.swing.JTextField();
        jLabelCSLL = new javax.swing.JLabel();
        jTextFieldCSLL = new javax.swing.JTextField();
        jLabelCPRP = new javax.swing.JLabel();
        jTextFieldCPRP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setText("Cálculo de Impostos PJ");

        jLabelValorNotaFiscal.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabelValorNotaFiscal.setText("Nota Fiscal:");

        jTextFieldValorNotaFiscal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldValorNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorNotaFiscalActionPerformed(evt);
            }
        });

        jButtonCalcular.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jLabelISS.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabelISS.setText("ISS:");

        jTextFieldISS.setEditable(false);
        jTextFieldISS.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldISS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldISSActionPerformed(evt);
            }
        });

        jLabelCONFINS.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabelCONFINS.setText("CONFINS:");

        jTextFieldCONFINS.setEditable(false);
        jTextFieldCONFINS.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldCONFINS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCONFINSActionPerformed(evt);
            }
        });

        jLabelPIS.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabelPIS.setText("PIS:");

        jTextFieldPIS.setEditable(false);
        jTextFieldPIS.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldPIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPISActionPerformed(evt);
            }
        });

        jLabelCSLL.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabelCSLL.setText("CSLL:");

        jTextFieldCSLL.setEditable(false);
        jTextFieldCSLL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldCSLL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCSLLActionPerformed(evt);
            }
        });

        jLabelCPRP.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabelCPRP.setText("CPRP:");

        jTextFieldCPRP.setEditable(false);
        jTextFieldCPRP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldCPRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPRPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelValorNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldValorNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCalcular))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelISS, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCPRP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCSLL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCSLL, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldCPRP, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(138, 138, 138))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldISS, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(135, 135, 135))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelPIS, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(102, 102, 102)
                                    .addComponent(jTextFieldPIS))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelCONFINS, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(jTextFieldCONFINS, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabelTitulo)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelTitulo)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorNotaFiscal)
                    .addComponent(jTextFieldValorNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelISS)
                    .addComponent(jTextFieldISS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCONFINS)
                    .addComponent(jTextFieldCONFINS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPIS)
                    .addComponent(jTextFieldPIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCSLL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCSLL, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCPRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPRP))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldValorNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorNotaFiscalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorNotaFiscalActionPerformed

    private void jTextFieldISSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldISSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldISSActionPerformed

    private void jTextFieldCONFINSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCONFINSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCONFINSActionPerformed

    private void jTextFieldPISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPISActionPerformed

    private void jTextFieldCSLLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCSLLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCSLLActionPerformed

    private void jTextFieldCPRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPRPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPRPActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // Capturando o valor da nota digitado pelo usuário.
        double nf = Double.parseDouble(jTextFieldValorNotaFiscal.getText());

        //Calculando os impostos e mostrando os cálculos na tela 
        NumberFormat formatoMoeda = NumberFormat.getCurrencyInstance();
        jTextFieldISS.setText(formatoMoeda.format((nf * 0.02)));
        jTextFieldCONFINS.setText((nf > 5000) ? formatoMoeda.format((nf * 0.03)) : "ISENTO");
        jTextFieldPIS.setText((nf > 5000) ? formatoMoeda.format((nf * 0.0065)) : "ISENTO");
        jTextFieldCSLL.setText(formatoMoeda.format((nf * 0.0188)));
        jTextFieldCPRP.setText(formatoMoeda.format((nf * 0.025)));
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoImpostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoImpostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoImpostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoImpostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculoImpostos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabelCONFINS;
    private javax.swing.JLabel jLabelCPRP;
    private javax.swing.JLabel jLabelCSLL;
    private javax.swing.JLabel jLabelISS;
    private javax.swing.JLabel jLabelPIS;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelValorNotaFiscal;
    private javax.swing.JTextField jTextFieldCONFINS;
    private javax.swing.JTextField jTextFieldCPRP;
    private javax.swing.JTextField jTextFieldCSLL;
    private javax.swing.JTextField jTextFieldISS;
    private javax.swing.JTextField jTextFieldPIS;
    private javax.swing.JTextField jTextFieldValorNotaFiscal;
    // End of variables declaration//GEN-END:variables
}
